-- MySQL Script generated by MySQL Workbench
-- Fri Oct  9 13:24:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TaskForce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TaskForce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TaskForce` DEFAULT CHARACTER SET utf8 ;
USE `TaskForce` ;

-- -----------------------------------------------------
-- Table `TaskForce`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`user` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `dt_add` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskForce`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`category` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `icon` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskForce`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`city` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `lat` DOUBLE NULL,
  `long` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskForce`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`status` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `translate` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `TaskForce`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`task` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `category_id` INT UNSIGNED NULL,
  `city_id` INT NULL,
  `address` VARCHAR(45) NULL,
  `budget` DECIMAL(10,2) NULL,
  `expire` DATETIME NULL,
  `description` TEXT NULL,
  `customer_id` INT UNSIGNED NULL,
  `status_id` INT NOT NULL,
  `status_execution` TINYINT(1) NULL,
  `replies_id` INT NOT NULL,
  `lat` DOUBLE NULL,
  `long` DOUBLE NULL,
  `executor_id` INT UNSIGNED NULL,
  `dt_add` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `catagory_idx` (`category_id` ASC) VISIBLE,
  INDEX `user_idx` (`customer_id` ASC) VISIBLE,
  INDEX `city_idx` (`city_id` ASC) VISIBLE,
  INDEX `fk_task_executor_idx` (`executor_id` ASC) VISIBLE,
  INDEX `fk_task_status_idx` (`status_id` ASC) VISIBLE,
  CONSTRAINT `fk_task_catagory`
    FOREIGN KEY (`category_id`)
    REFERENCES `TaskForce`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_task_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `TaskForce`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_task_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `TaskForce`.`city` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_task_executor`
    FOREIGN KEY (`executor_id`)
    REFERENCES `TaskForce`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_status`
    FOREIGN KEY (`status_id`)
    REFERENCES `TaskForce`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskForce`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`file` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `task_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `task_idx` (`task_id` ASC) VISIBLE,
  CONSTRAINT `fk_file_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `TaskForce`.`task` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskForce`.`replies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`replies` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`replies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NULL,
  `user_id` INT NULL,
  `price` DECIMAL(10,2) NULL,
  `description` TEXT NULL,
  `dt_add` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_response_task_idx` (`task_id` ASC) VISIBLE,
  INDEX `fk_response_executor_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_response_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `TaskForce`.`task` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_response_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `TaskForce`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskForce`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`message` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sender_id` INT NULL,
  `recipient_id` INT NULL,
  `message` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `recipient_idx` (`recipient_id` ASC) VISIBLE,
  INDEX `sender_idx` (`sender_id` ASC) VISIBLE,
  CONSTRAINT `fk_message_recipient`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `TaskForce`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_message_sender`
    FOREIGN KEY (`sender_id`)
    REFERENCES `TaskForce`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskForce`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`photo` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`photo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_photo_1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_photo_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `TaskForce`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskForce`.`opinions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`opinions` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`opinions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dt_add` DATETIME NULL,
  `rate` INT NULL,
  `id_task` INT UNSIGNED NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_opinions_task`
    FOREIGN KEY (`id`)
    REFERENCES `TaskForce`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `TaskForce`.`specialization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`specialization` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`specialization` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_specialization_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_specialization_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_specialization_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `TaskForce`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_specialization_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `TaskForce`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `TaskForce`.`profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`profiles` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`profiles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NULL,
  `bd` DATE NULL,
  `about` TEXT NULL,
  `phone` VARCHAR(45) NULL,
  `telegram` VARCHAR(45) NULL,
  `counter_failed_tasks` INT NULL,
  `specialization_id` INT NULL,
  `city_id` INT NULL,
  `avatar` VARCHAR(45) NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profiles_city_idx` (`city_id` ASC) VISIBLE,
  INDEX `fk_profiles_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_profiles_specializ_idx` (`specialization_id` ASC) VISIBLE,
  CONSTRAINT `fk_profiles_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `TaskForce`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profiles_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `TaskForce`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profiles_specializ`
    FOREIGN KEY (`specialization_id`)
    REFERENCES `TaskForce`.`specialization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
