-- MySQL Script generated by MySQL Workbench
-- Чт 30 апр 2020 13:41:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TaskForce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TaskForce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TaskForce` DEFAULT CHARACTER SET utf8 ;
USE `TaskForce` ;

-- -----------------------------------------------------
-- Table `TaskForce`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`city` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskForce`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`user` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  `city_id` INT NULL,
  `specialization` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `skype` VARCHAR(45) NULL,
  `telegram` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `registration_date` DATETIME NOT NULL,
  `counter_failed_tasks` VARCHAR(45) NULL,
  `avatar` VARCHAR(128) NULL,
  PRIMARY KEY (`id`),
  INDEX `city_idx` (`city_id` ASC),
  CONSTRAINT `fk_user_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `TaskForce`.`city` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskForce`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`category` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskForce`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`task` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brief_description` VARCHAR(45) NULL,
  `category_id` INT NULL,
  `city_id` INT NULL,
  `address` VARCHAR(45) NULL,
  `budget` DECIMAL(10,2) NULL,
  `date_execution` DATETIME NULL,
  `details_task` TEXT NULL,
  `customer_id` INT NULL,
  `status` VARCHAR(45) NULL,
  `estimation` INT NULL,
  `status_execution` TINYINT(1) NULL,
  `comment` VARCHAR(45) NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `user_id` INT NOT NULL,
  `response_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `catagory_idx` (`category_id` ASC),
  INDEX `user_idx` (`customer_id` ASC),
  INDEX `city_idx` (`city_id` ASC),
  CONSTRAINT `fk_task_catagory`
    FOREIGN KEY (`category_id`)
    REFERENCES `TaskForce`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_task_user`
    FOREIGN KEY (`customer_id`)
    REFERENCES `TaskForce`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_task_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `TaskForce`.`city` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskForce`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`file` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` CHAR(128) NOT NULL,
  `task_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `task_idx` (`task_id` ASC),
  CONSTRAINT `fk_file_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `TaskForce`.`task` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskForce`.`response`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`response` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`response` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NULL,
  `executor_id` INT NULL,
  `price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_response_task_idx` (`task_id` ASC),
  INDEX `fk_response_executor_idx` (`executor_id` ASC),
  CONSTRAINT `fk_response_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `TaskForce`.`task` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_response_executor`
    FOREIGN KEY (`executor_id`)
    REFERENCES `TaskForce`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskForce`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`Message` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`Message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sender_id` INT NULL,
  `recipient_id` INT NULL,
  `message` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `recipient_idx` (`recipient_id` ASC),
  INDEX `sender_idx` (`sender_id` ASC),
  CONSTRAINT `fk_message_recipient`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `TaskForce`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_message_sender`
    FOREIGN KEY (`sender_id`)
    REFERENCES `TaskForce`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskForce`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskForce`.`photo` ;

CREATE TABLE IF NOT EXISTS `TaskForce`.`photo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` CHAR(128) NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_photo_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_photo_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `TaskForce`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
